services:
  solo_website:
    build: .
    container_name: solo_website
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solo_website.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.solo_website.entrypoints=websecure"
      - "traefik.http.routers.solo_website.tls.certresolver=le"
      - "traefik.http.services.solo_website.loadbalancer.server.port=${PORT}"
      - "traefik.http.middlewares.solo_website-hsts.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.solo_website-hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.solo_website-hsts.headers.stsPreload=true"
      - "traefik.http.routers.solo_website.middlewares=solo_website-hsts@docker"
    networks:
      - web
    expose:
      - "${PORT}"

networks:
  web:
    external: true
